name: .NET Core CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.0.x
          10.0.x

    - name: Restore dependencies
      run: dotnet restore "part3 POE.slnx"

    - name: Build project
      run: dotnet build "part3 POE.slnx" --configuration Release --no-restore
